name: Release Linux

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
        
      - name: Restore
        run: dotnet restore
        working-directory: ./GithubBackup
        
      - name: Build
        run: dotnet build GithubBackup.sln --configuration Release --no-restore
        working-directory: ./GithubBackup
        
      - name: Test
        run: dotnet test GithubBackup.sln --configuration Release --no-restore
        working-directory: ./GithubBackup
        
      - name: Publish
        run: dotnet publish GithubBackup.Cli/GithubBackup.Cli.csproj --configuration Release --output publish/win-x64 --runtime linux-x64 --self-contained
        working-directory: ./GithubBackup
        
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./GithubBackup/publish/linux-x64/ghb
          asset_name: linux-x64/ghb.exe
          asset_content_type: application/octet-stream