name: Test OSX

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
        
      - name: Restore
        run: dotnet restore
        
      - name: Build
        run: dotnet build GithubBackup.sln --configuration Release --no-restore
        
      - name: Test
        run: dotnet test GithubBackup.sln --configuration Release --no-restore